### ISSUE TITLE
windows 7 build error

### ISSUE THREAD

**Issue by antanse** [dazoe/ed25519#15]
when I install this package, I meet with the following errors.
```javascript
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\albert\NetCode\NodejsWorkspace\BCJS>npm install ed25519

> ed25519@0.0.4 install C:\albert\NetCode\NodejsWorkspace\BCJS\node_modules\ed25519
> node-gyp rebuild


C:\albert\NetCode\NodejsWorkspace\BCJS\node_modules\ed25519>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\nod
e-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolse
t = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Vis
ual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\albert\NetCode\NodejsWorksp
ace\BCJS\node_modules\ed25519\build\ed25519.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebui
ld"
gyp ERR! cwd C:\albert\NetCode\NodejsWorkspace\BCJS\node_modules\ed25519
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN bcjs@0.1.3 No description
npm WARN bcjs@0.1.3 No repository field.
npm WARN bcjs@0.1.3 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ed25519"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ed25519@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519@0.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ed25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ed25519
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\albert\NetCode\NodejsWorkspace\BCJS\npm-debug.log
```
could you please take a look at this issue

**Comment by antanse** [comment]
it seems like that I need to install vs 2015, but my visual studio version is 2013 in my laptop, do we have a solution for vs 2013?

**Comment by chineselyw** [comment]
my visual studio version is 2015 in my laptop，but this issue still exist。

**Comment by sgehrman** [comment]
same problem here, but it seemed to work sometimes.  Any solution?

warning Error running install script for optional dependency: "f:\\Github\\eth-client\\node_modules\\ed25519: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: f:\\Github\\eth-client\\node_modules\\ed25519\nOutput:\nf:\\Github\\eth-client\\node_modules\\ed25519>if not defined npm_config_node_gyp (node \"c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.0 | win32 | x64\ngyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR\ngyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR\ngyp info spawn C:\\Users\\Steve\\.windows-build-tools\\python27\\python.exe\ngyp info spawn args [ 'c:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=auto',\ngyp info spawn args   '-I',\ngyp info spawn args   'f:\\\\Github\\\\eth-client\\\\node_modules\\\\ed25519\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'c:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\Steve\\\\.node-gyp\\\\8.9.0\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\Steve\\\\.node-gyp\\\\8.9.0',\ngyp info spawn args   '-Dnode_gyp_dir=c:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Steve\\\\.node-gyp\\\\8.9.0\\\\<(target_arch)\\\\node.lib',\ngyp info spawn args   '-Dmodule_root_dir=f:\\\\Github\\\\eth-client\\\\node_modules\\\\ed25519',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'f:\\\\Github\\\\eth-client\\\\node_modules\\\\ed25519\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\ngyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR\ngyp info spawn C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.exe\ngyp info spawn args [ 'build/binding.sln',\ngyp info spawn args   '/clp:Verbosity=minimal',\ngyp info spawn args   '/nologo',\ngyp info spawn args   '/p:Configuration=Release;Platform=x64' ]\nBuilding the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.\r\n  keypair.c\r\n  sign.c\r\n  open.c\r\n  crypto_verify_32.c\r\n  ge_double_scalarmult.c\r\n  ge_frombytes.c\r\n  ge_scalarmult_base.c\r\n  ge_precomp_0.c\r\n  ge_p2_0.c\r\n  ge_p2_dbl.c\r\n  ge_p3_0.c\r\n  ge_p3_dbl.c\r\n..\\src\\ed25519\\ge_scalarmult_base.c(19): warning C4244: 'return': conversion from 'unsigned __int64' to 'unsigned char', possible loss of data [f:\\Github\\eth-client\\node_modules\\ed25519\\build\\ed25519.vcxproj]\r\n  ge_p3_to_p2.c\r\n  ge_p3_to_cached.c\r\n  ge_p3_tobytes.c\r\n  ge_madd.c\r\n  ge_add.c\r\n  ge_msub.c\r\n  ge_sub.c\r\n  ge_p1p1_to_p3.c\r\n  ge_p1p1_to_p2.c\r\n  ge_tobytes.c\r\n  fe_0.c\r\n  f

**Comment by erikma** [comment]
I added Windows machine setup instructions to the latest README that include installing the VS 2017 Tools installer (not all of Visual Studio), please retry with head master as those instructions are working for me on Windows 10 1909.
