### ISSUE TITLE
Install error on CentOS 6

### ISSUE THREAD

**Issue by jacobtomlinson** [dazoe/ed25519#6]
```
# npm install ed25519
npm http GET https://registry.npmjs.org/ed25519
npm http 304 https://registry.npmjs.org/ed25519
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings

> ed25519@0.0.3 install /tmp/node_modules/ed25519
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/lib/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2736, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 386, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 238, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-504.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/ed25519
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by KenanSulayman** [comment]
Your Python version isn't 2.7, right?

**Comment by jacobtomlinson** [comment]
No it's 2.6.6 which is the default in Red Hat based operating systems.
